import type { Metadata } from "next";
import "./globals.css";
import Header from "./_partials/Header";
import Navigation from "./_partials/Navigation";
import { AuthProvider } from "./_contexts/AuthContext";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <AuthProvider>
                    <Header />
                    <div className="my-16 p-4">{children}</div>
                    <Navigation />
                </AuthProvider>
            </body>
        </html>
    );
}
