import type { Metadata } from "next";
import "./globals.css";
import Header from "./partials/Header";
import Navigation from "./partials/Navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="my-16 p-4">{children}</div>
        <Navigation />
      </body>
    </html>
  );
}
